services:
  rethinkdb:
    image: rethinkdb:2.4.2
    restart: unless-stopped
    command: rethinkdb --bind all --cache-size 512
    volumes:
      - rethinkdb-data:/data

  adb:
    build:
      context: .
      dockerfile: Dockerfile-adb
    image: devicefarmer/adb:stf-local
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    command:
      - sh
      - -c
      - >-
        adb -P 5037 server nodaemon &
        server_pid=$$!;
        socat TCP-LISTEN:5038,bind=172.18.0.1,reuseaddr,fork
        TCP:127.0.0.1:5037 &
        until adb -P 5037 connect 127.0.0.1:5555 |
        grep -Eq 'connected|already connected'; do sleep 1; done;
        wait $$server_pid

  stf:
    build:
      context: .
      dockerfile: Dockerfile
    image: devicefarmer/stf:local
    restart: unless-stopped
    depends_on:
      - rethinkdb
      - adb
    environment:
      TZ: ${TZ:-Asia/Jerusalem}
      RETHINKDB_PORT_28015_TCP: tcp://rethinkdb:28015
      STF_ADMIN_EMAIL: ${STF_ADMIN_EMAIL:-admin@localhost}
      STF_ADMIN_NAME: ${STF_ADMIN_NAME:-STF Admin}
    extra_hosts:
      - host.docker.internal:172.18.0.1
    command:
      - stf
      - local
      - --auth-type
      - guest
      - --port
      - "7100"
      - --public-ip
      - ${STF_PUBLIC_IP:-127.0.0.1}
      - --adb-host
      - host.docker.internal
      - --adb-port
      - "5038"
      - --provider-min-port
      - "7400"
      - --provider-max-port
      - "7500"
    ports:
      - 127.0.0.1:7100:7100
      - 127.0.0.1:7110:7110
      - 127.0.0.1:7400-7500:7400-7500

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

volumes:
  rethinkdb-data:
